# Generated by Django 4.2.2 on 2023-12-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_author',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
