# Generated by Django 4.2.2 on 2023-12-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_author_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bought_book',
            field=models.TextField(blank=True, null=True),
        ),
    ]
