# Generated by Django 4.2.2 on 2023-12-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customuser_bought_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bought_book',
            field=models.TextField(default=''),
        ),
    ]
